### ISSUE TITLE
SearchQueryIterator: Propagate error to caller?

### ISSUE THREAD

**Issue by FilWisher** [guardian/gocapiclient#6]
In `GuardianContentClient.SearchQueryIterator`, the process exits if one of the page requests fails [0]:

``` go
err := contentClient.GetResponse(query)

if err != nil {
    log.Fatal(err)
}
```

In this case, the library will exit the process itself. I wonder whether this is surprising behaviour. It seems to me that the responsibility for handling the error lies with library user. Then they can either exit the process or retry.

Should this method attempt to propagate the error to the caller?

---

[0] https://github.com/guardian/gocapiclient/blob/master/gocapiclient.go#L70

**Comment by kenoir** [comment]
Yeah, I think you're right. Do you reckon wrapping the response to return the potential error also is better behaviour?

e.g.

``` go
type PageResponse struct {
  err error
  searchResponse *content.SearchResponse
}
```

So the signature of `SearchQueryIterator` becomes:

``` go
func (contentClient GuardianContentClient) SearchQueryIterator(query *queries.SearchQuery) <-chan *PageResponse
```

**Comment by kenoir** [comment]
Fixed in https://github.com/guardian/gocapiclient/pull/7

**Comment by FilWisher** [comment]
:+1: I think that is better solution
